name: Sync to Gitee

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        run: |
          git remote add gitee https://nickcdut:${{ secrets.GITEE_TOKEN }}@gitee.com/nickcdut/shuyu.git
          git push -f gitee main
